# Generated by Django 5.2.17 on 2026-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('ACTIVE', 'Active'), ('PENDING_APPROVAL', 'Pending Approval'), ('VERIFIED', 'Verified & Endorsed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='PROCESSING', max_length=20),
        ),
    ]
