# Generated by Django 5.2.17 on 2026-09-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='storage_location_name',
            field=models.CharField(blank=True, default='', help_text='Vault / rack / locker storage location text', max_length=255),
        ),
    ]
