# Generated by Django 5.2.17 on 2026-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, default='FIR', max_length=100),
        ),
    ]
