# Generated by Django 5.2.17 on 2026-08-24 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('VIEW', 'View'), ('EDIT', 'Edit'), ('SHARE', 'Share'), ('APPROVE', 'Approve'), ('DELETE', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document_hash', models.CharField(max_length=64)),
                ('previous_log_hash', models.CharField(max_length=64)),
                ('current_log_hash', models.CharField(max_length=64)),
                ('signature', models.TextField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('BIOMETRIC', 'Biometric'), ('WEBAUTHN', 'WebAuthn'), ('OTP', 'OTP'), ('PASSWORD', 'Password'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'timestamp'], name='audit_audit_documen_3ae8ab_idx')],
            },
        ),
    ]
