# Generated by Django 5.2.17 on 2026-09-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('cases', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.case'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='last_verification_result',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['case', 'timestamp'], name='audit_audit_case_id_f0a894_idx'),
        ),
    ]
