# Generated by Django 5.2.17 on 2026-09-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_auditlog_case_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('VIEW', 'View'), ('EDIT', 'Edit'), ('SHARE', 'Share'), ('APPROVE', 'Approve'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('REGISTER', 'Register Evidence'), ('MOVE', 'Movement Request'), ('RELEASE', 'Evidence Release'), ('RECEIVE', 'Evidence Receive'), ('REJECT', 'Reject'), ('SEAL', 'Seal Operation'), ('CONDITION', 'Condition Change'), ('USER', 'User Administration'), ('CASE_CREATE', 'Case Creation'), ('CASE_ASSIGN', 'Case Assignment'), ('CASE_UPDATE', 'Case Update')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.document'),
        ),
    ]
