# Generated by Django 5.2.17 on 2026-09-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action_alter_auditlog_document'),
        ('cases', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='document_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('VIEW', 'View'), ('EDIT', 'Edit'), ('SHARE', 'Share'), ('APPROVE', 'Approve'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('REGISTER', 'Register Evidence'), ('MOVE', 'Movement Request'), ('RELEASE', 'Evidence Release'), ('RECEIVE', 'Evidence Receive'), ('REJECT', 'Reject'), ('SEAL', 'Seal Operation'), ('CONDITION', 'Condition Change'), ('USER', 'User Administration'), ('CASE_CREATE', 'Case Creation'), ('CASE_ASSIGN', 'Case Assignment'), ('CASE_UPDATE', 'Case Update'), ('CASE_DELETE', 'Case Deletion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document'),
        ),
    ]
