# Generated by Django 5.2.17 on 2026-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_case_number_auditlog_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('VIEW', 'View'), ('EDIT', 'Edit'), ('SHARE', 'Share'), ('APPROVE', 'Approve'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('REGISTER', 'Register Evidence'), ('MOVE', 'Movement Request'), ('RELEASE', 'Evidence Release'), ('RECEIVE', 'Evidence Receive'), ('REJECT', 'Reject'), ('SEAL', 'Seal Operation'), ('CONDITION', 'Condition Change'), ('USER', 'User Administration'), ('CASE_CREATE', 'Case Creation'), ('CASE_ASSIGN', 'Case Assignment'), ('CASE_UPDATE', 'Case Update'), ('CASE_DELETE', 'Case Deletion'), ('FINAL_REPORT', 'Final Case Report')], max_length=20),
        ),
    ]
